// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

/*
Package hello is a generated protocol buffer package.

It is generated from these files:
	hello.proto

It has these top-level messages:
	Person
	Reply
*/
package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	BirthDate string `protobuf:"bytes,2,opt,name=birth_date,json=birthDate" json:"birth_date,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

type Reply struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int64  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Reply) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*Person)(nil), "hello.Person")
	proto.RegisterType((*Reply)(nil), "hello.Reply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hello service

type HelloClient interface {
	GetAges(ctx context.Context, opts ...grpc.CallOption) (Hello_GetAgesClient, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) GetAges(ctx context.Context, opts ...grpc.CallOption) (Hello_GetAgesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Hello_serviceDesc.Streams[0], c.cc, "/hello.Hello/GetAges", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloGetAgesClient{stream}
	return x, nil
}

type Hello_GetAgesClient interface {
	Send(*Person) error
	Recv() (*Reply, error)
	grpc.ClientStream
}

type helloGetAgesClient struct {
	grpc.ClientStream
}

func (x *helloGetAgesClient) Send(m *Person) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloGetAgesClient) Recv() (*Reply, error) {
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Hello service

type HelloServer interface {
	GetAges(Hello_GetAgesServer) error
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_GetAges_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServer).GetAges(&helloGetAgesServer{stream})
}

type Hello_GetAgesServer interface {
	Send(*Reply) error
	Recv() (*Person, error)
	grpc.ServerStream
}

type helloGetAgesServer struct {
	grpc.ServerStream
}

func (x *helloGetAgesServer) Send(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloGetAgesServer) Recv() (*Person, error) {
	m := new(Person)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAges",
			Handler:       _Hello_GetAges_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x4f, 0xc1, 0xaa, 0xc2, 0x30,
	0x10, 0x7c, 0x79, 0xb5, 0x95, 0xae, 0x0a, 0x92, 0x53, 0x11, 0x14, 0xe9, 0xa9, 0x07, 0x0d, 0xa2,
	0x78, 0xf2, 0x64, 0x11, 0xf4, 0x58, 0xfa, 0x03, 0x92, 0xe2, 0xb6, 0x0d, 0xc4, 0xa4, 0xa4, 0x41,
	0xf0, 0xef, 0xa5, 0x89, 0x47, 0x6f, 0x33, 0xbb, 0x3b, 0xb3, 0x33, 0x30, 0x69, 0x51, 0x4a, 0xcd,
	0x3a, 0xa3, 0xad, 0xa6, 0xa1, 0x23, 0xe9, 0x09, 0xa2, 0x02, 0x4d, 0xaf, 0x15, 0xa5, 0x30, 0x52,
	0xfc, 0x89, 0x09, 0x59, 0x93, 0x2c, 0x2e, 0x1d, 0xa6, 0x4b, 0x80, 0x4a, 0x18, 0xdb, 0xde, 0x1f,
	0xdc, 0x62, 0xf2, 0xef, 0x36, 0xb1, 0x9b, 0x5c, 0xb8, 0xc5, 0x74, 0x0b, 0x61, 0x89, 0x9d, 0x7c,
	0xff, 0xd4, 0xce, 0x21, 0xe0, 0x8d, 0x17, 0x05, 0xe5, 0x00, 0xf7, 0x47, 0x08, 0x6f, 0xc3, 0x53,
	0xba, 0x81, 0xf1, 0x15, 0xed, 0xb9, 0xc1, 0x9e, 0xce, 0x98, 0x0f, 0xe5, 0x43, 0x2c, 0xa6, 0x5f,
	0xea, 0x6c, 0xd3, 0xbf, 0x8c, 0xec, 0x48, 0xce, 0x60, 0xa5, 0xd0, 0xb2, 0x4a, 0xbc, 0x84, 0x94,
	0xc8, 0x6a, 0xa9, 0x0d, 0x2a, 0xcb, 0x8c, 0xa8, 0x6b, 0x7f, 0x9d, 0x83, 0xb3, 0x2d, 0x86, 0x5e,
	0x05, 0xa9, 0x22, 0x57, 0xf0, 0xf0, 0x09, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x1b, 0x98, 0xdc, 0xef,
	0x00, 0x00, 0x00,
}
